# Generated by Django 5.2.14 on 2026-07-01 16:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("return_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("awaiting_return", "Awaiting return"),
                            ("in_transit", "In transit"),
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("refunded", "Refunded"),
                            ("replaced", "Replaced"),
                            ("completed", "Completed"),
                        ],
                        default="pending_review",
                        max_length=30,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Damaged"),
                            ("wrong_item", "Wrong item"),
                            ("missing_item", "Missing item"),
                            ("defective", "Defective"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("refund", "Refund"),
                            ("replacement", "Replacement"),
                            ("store_credit", "Store credit"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "refund_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="orders.order",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Damaged"),
                            ("wrong_item", "Wrong item"),
                            ("missing_item", "Missing item"),
                            ("defective", "Defective"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("condition_notes", models.TextField(blank=True, default="")),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="returns.returnrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("image", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReturnStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=30, null=True)),
                ("to_status", models.CharField(max_length=30)),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["return_number"], name="returns_ret_return__7635ad_idx"),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["order"], name="returns_ret_order_i_30fb33_idx"),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["customer"], name="returns_ret_custome_4c31cc_idx"),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["status"], name="returns_ret_status_d3fc8b_idx"),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["created_at"], name="returns_ret_created_a48112_idx"),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.UniqueConstraint(
                fields=("return_request", "order_item"), name="unique_return_item"
            ),
        ),
    ]
