# Generated by Django 5.2.14 on 2026-07-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnstatushistory",
            name="from_status",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
