# Generated by Django 5.2.14 on 2026-07-01 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockreservation",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_reservations",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_reservations",
                to="catalog.variant",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["variant"], name="inventory_i_variant_f4df33_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["transaction_type"], name="inventory_i_transac_2eccee_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["created_at"], name="inventory_i_created_670884_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["reference_type", "reference_id"], name="inventory_i_referen_ace22e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["variant"], name="inventory_s_variant_fdfe16_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["user"], name="inventory_s_user_id_c154f4_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["order"], name="inventory_s_order_i_25b0c4_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["status"], name="inventory_s_status_79107d_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["expires_at"], name="inventory_s_expires_9d6a1b_idx"),
        ),
    ]
