# Generated by Django 5.2.14 on 2026-07-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("email_verification", "Email verification"),
                    ("password_reset", "Password reset"),
                    ("phone_verification", "Phone verification"),
                    ("phone_change", "Phone change"),
                ],
                max_length=32,
            ),
        ),
    ]
