# Generated by Django 5.2.14 on 2026-07-01 16:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_per_kg", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("estimated_min_days", models.PositiveIntegerField(default=1)),
                ("estimated_max_days", models.PositiveIntegerField(default=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["base_price"],
            },
        ),
        migrations.CreateModel(
            name="OrderShippingAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(blank=True, default="", max_length=255)),
                ("postal_code", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=255)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_address",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("carrier", models.CharField(max_length=255)),
                ("tracking_number", models.CharField(max_length=255, unique=True)),
                ("tracking_url", models.URLField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("in_transit", "In transit"),
                            ("out_for_delivery", "Out for delivery"),
                            ("delivered", "Delivered"),
                            ("exception", "Exception"),
                        ],
                        default="processing",
                        max_length=30,
                    ),
                ),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["order"], name="shipping_or_order_i_246ba9_idx"),
                    models.Index(fields=["tracking_number"], name="shipping_or_trackin_8a3acb_idx"),
                    models.Index(fields=["status"], name="shipping_or_status_5ea972_idx"),
                ],
            },
        ),
    ]
