# Generated by Django 5.2.14 on 2026-07-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coupons", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponredemption",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_redemptions",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(fields=["coupon"], name="coupons_cou_coupon__325467_idx"),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(fields=["customer"], name="coupons_cou_custome_9a20e0_idx"),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(
                fields=["coupon", "customer"], name="coupons_cou_coupon__36a9e5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="couponredemption",
            constraint=models.UniqueConstraint(
                fields=("coupon", "order"), name="unique_coupon_order"
            ),
        ),
    ]
